FROM clojure:tools-deps

WORKDIR /app

# Using Debian, as root
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -

RUN apt-get update -yq \
    && apt-get install curl gnupg -yq \
    && apt-get install nodejs -yq \
	&& apt-get install npm -yq

COPY package.json ./package.json

RUN npm i

COPY . .

CMD npx shadow-cljs server