version: '3.7'
services:
  fulcro-backend:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: fulcro-backend
    image: fulcro-backend:dev
    build:
      context: .
      dockerfile: Dockerfile.backend.development
    volumes:
      - .:/app
      - m2:/app/.m2
    ports:
      - 3000:3000
      - 9001:9001
  fulcro-frontend:
    container_name: fulcro-frontend
    image: fulcro-frontend:dev
    build:
      context: .
      dockerfile: Dockerfile.frontend.development
    volumes:
      - .:/app
      - m2:/app/.m2
      - node_modules:/app/node_modules
    ports:
      - 8022:8022
      - 8023:8023
      - 9000:9000
      - 9630:9630
volumes:
  node_modules:
  m2:
