version: '3.7'
services:
  fulcro-website:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: fulcro-website
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - m2:/app/.m2
    ports:
      - 8080:8080
volumes:
  node_modules:
  m2:
